name: 'EC Open AI Base'
description: 'Installs and configures base requirements for AI integration'
type: 'Site'

install:
  # AI base modules
  - ai
  - ai_provider_openai
  - ai_provider_anthropic
  - ai_image_alt_text
  - key

